import type { Chat, Message } from '../types';

export const mockChats: Chat[] = [
  {
    id: '1',
    name: 'Алексей Петров',
    lastMessage: 'Привет! Как дела?',
    avatar: '',
    unreadCount: 2,
    timestamp: '12:30',
    isOnline: true,
  },
  {
    id: '2',
    name: 'Мария Иванова',
    lastMessage: 'Жду тебя в офисе',
    avatar: '',
    unreadCount: 0,
    timestamp: '11:15',
    isOnline: false,
  },
  {
    id: '3',
    name: 'Ирина Солнцева',
    lastMessage: 'Стою в пробке',
    avatar: '',
    unreadCount: 0,
    timestamp: '13:13',
    isOnline: false,
  },
  {
    id: '4',
    name: 'Георгий Жуков',
    lastMessage: 'На тренировке',
    avatar: '',
    unreadCount: 1,
    timestamp: '09:50',
    isOnline: false,
  },
  {
    id: '5',
    name: 'Петр Васильков',
    lastMessage: 'Что там на Youtube',
    avatar: '',
    unreadCount: 3,
    timestamp: '06:09',
    isOnline: true,
  },
];

export const mockMessages: Message[] = [
  {
    id: '1',
    text: 'Привет! Как дела?',
    timestamp: '12:30',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '2',
    text: 'Привет! Все отлично, спасибо!',
    timestamp: '12:31',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '3',
    text: 'Отлично слышать! Ты видел новое обновление мессенджера?',
    timestamp: '12:32',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '4',
    text: 'Да, уже пробую. Очень удобно!',
    timestamp: '12:33',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '5',
    text: 'Кстати, завтра встреча в 15:00, не забудь!',
    timestamp: '12:35',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '6',
    text: 'Записал в календарь. Буду!',
    timestamp: '12:36',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '7',
    text: 'Супер! Нужно ли что-то подготовить?',
    timestamp: '12:37',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '8',
    text: 'Да, возьми, пожалуйста, последние отчёты.',
    timestamp: '12:38',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '9',
    text: 'Хорошо, подготовлю.',
    timestamp: '12:39',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '10',
    text: 'Спасибо! 😊',
    timestamp: '12:40',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '11',
    text: 'Как тебе погода сегодня?',
    timestamp: '13:05',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '12',
    text: 'Нормально, хоть и дождливо. Но я с зонтом!',
    timestamp: '13:07',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '13',
    text: 'Умница! 😄',
    timestamp: '13:08',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '14',
    text: 'Ты уже обедал?',
    timestamp: '13:15',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '15',
    text: 'Только что закончил. Было вкусно!',
    timestamp: '13:16',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '16',
    text: 'Здорово! Я только собираюсь.',
    timestamp: '13:17',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
  {
    id: '17',
    text: 'Приятного аппетита!',
    timestamp: '13:18',
    isOwn: true,
    senderId: 'me',
    senderName: 'Я',
    status: 'read',
  },
  {
    id: '18',
    text: 'Спасибо! Кстати, ты смотрел тот фильм, что я рекомендовал?',
    timestamp: '14:02',
    isOwn: false,
    senderId: '1',
    senderName: 'Алексей Петров',
  },
];
